// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plfpczvnqmvqpmsbjrra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsZnBjenZucW12cXBtc2JqcnJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyOTIwMjEsImV4cCI6MjA3Njg2ODAyMX0.k0JoQvzptgBNr4pBSOQjAE9q_Mge6gVdCFd471onPBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});